### ISSUE TITLE
what if two user run command 'kubevpn proxy' almost in the same time

### ISSUE THREAD

**Issue by kyr1eeee** [kubenetworks/kubevpn#135]
Hello again.
A few days ago, I ran the command 'kubevpn proxy' against two deploymeny in the same namespace, after the command, i found that two pod's tun ip were same(both were 223.254.0.104). 
I think this is because of two webhook handler accessing one configmap concurrently.
Is there any optimization for this?

**Comment by wencaiwulue** [comment]
Yes, maybe it's a bug. you mean two pod controlled by two different deployment in same namespace,  but have same tunIP right? can you provide the pod manifest?

**Comment by kyr1eeee** [comment]
Sorry i didn't make myself clear.
Yes, it's two pod controlled by two different deployment in same namespace.
there is pods vpn container manifest:
```yaml
vpn:
    Container ID:  docker://7286c2e659534f047f59aebb38bade5f3f59e3a7a9a0a75d1a39943f2060e914
    Image:         xxx/kubevpn:v2.1.3
    Image ID:      docker-pullable://xxx/kubevpn@sha256:71a2d092b6b19b99fb5e2a7eb715a946d0ff03d9a72589f0550e4517adefe3fd
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:

      sysctl -w net.ipv4.ip_forward=1
      sysctl -w net.ipv6.conf.all.disable_ipv6=0
      sysctl -w net.ipv6.conf.all.forwarding=1
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      iptables -F
      ip6tables -F
      iptables -P INPUT ACCEPT
      ip6tables -P INPUT ACCEPT
      iptables -P FORWARD ACCEPT
      ip6tables -P FORWARD ACCEPT
      iptables -t nat -A PREROUTING ! -p icmp ! -s 127.0.0.1 ! -d ${CIDR4} -j DNAT --to 127.0.0.1:15006
      ip6tables -t nat -A PREROUTING ! -p icmp ! -s 0:0:0:0:0:0:0:1 ! -d ${CIDR6} -j DNAT --to [0:0:0:0:0:0:0:1]:15006
      iptables -t nat -A POSTROUTING ! -p icmp ! -s 127.0.0.1 ! -d ${CIDR4} -j MASQUERADE
      ip6tables -t nat -A POSTROUTING ! -p icmp ! -s 0:0:0:0:0:0:0:1 ! -d ${CIDR6} -j MASQUERADE
      kubevpn serve -L "tun:/localhost:8422?net=${TunIPv4}&route=${CIDR4}" -F "tcp://${TrafficManagerService}:10800"
    State:          Running
      Started:      Fri, 26 Jan 2024 17:03:24 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     256m
      memory:  256Mi
    Requests:
      cpu:     128m
      memory:  128Mi
    Environment Variables from:
      kubevpn-traffic-manager  Secret  Optional: false
    Environment:
      CIDR4:                  223.254.0.0/16
      CIDR6:                  efff:ffff:ffff:ffff::/64
      TunIPv4:                223.254.0.104/16
      TunIPv6:                efff:ffff:ffff:ffff:ffff:ffff:ffff:999d/64
      TrafficManagerService:  kubevpn-traffic-manager
      POD_NAMESPACE:          default (v1:metadata.namespace)
      POD_NAME:               cs-3004-f65d946b6-h7cq6 (v1:metadata.name)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-p7bwn (ro)
```

```yaml
vpn:
    Container ID:  docker://9fb80bba14fa589ce7cc93a7fbcdc643dd745d1e2182e1617a75a0c998cb7d4b
    Image:         xxx/kubevpn:v2.1.3
    Image ID:      docker-pullable://xxx/kubevpn@sha256:71a2d092b6b19b99fb5e2a7eb715a946d0ff03d9a72589f0550e4517adefe3fd
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:

      sysctl -w net.ipv4.ip_forward=1
      sysctl -w net.ipv6.conf.all.disable_ipv6=0
      sysctl -w net.ipv6.conf.all.forwarding=1
      update-alternatives --set iptables /usr/sbin/iptables-legacy
      iptables -F
      ip6tables -F
      iptables -P INPUT ACCEPT
      ip6tables -P INPUT ACCEPT
      iptables -P FORWARD ACCEPT
      ip6tables -P FORWARD ACCEPT
      iptables -t nat -A PREROUTING ! -p icmp ! -s 127.0.0.1 ! -d ${CIDR4} -j DNAT --to 127.0.0.1:15006
      ip6tables -t nat -A PREROUTING ! -p icmp ! -s 0:0:0:0:0:0:0:1 ! -d ${CIDR6} -j DNAT --to [0:0:0:0:0:0:0:1]:15006
      iptables -t nat -A POSTROUTING ! -p icmp ! -s 127.0.0.1 ! -d ${CIDR4} -j MASQUERADE
      ip6tables -t nat -A POSTROUTING ! -p icmp ! -s 0:0:0:0:0:0:0:1 ! -d ${CIDR6} -j MASQUERADE
      kubevpn serve -L "tun:/localhost:8422?net=${TunIPv4}&route=${CIDR4}" -F "tcp://${TrafficManagerService}:10800"
    State:          Running
      Started:      Fri, 26 Jan 2024 17:05:35 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     256m
      memory:  256Mi
    Requests:
      cpu:     128m
      memory:  128Mi
    Environment Variables from:
      kubevpn-traffic-manager  Secret  Optional: false
    Environment:
      CIDR4:                  223.254.0.0/16
      CIDR6:                  efff:ffff:ffff:ffff::/64
      TunIPv4:                223.254.0.104/16
      TunIPv6:                efff:ffff:ffff:ffff:ffff:ffff:ffff:999d/64
      TrafficManagerService:  kubevpn-traffic-manager
      POD_NAMESPACE:          default (v1:metadata.namespace)
      POD_NAME:               contact-3004-69f475dcc6-xjp9r (v1:metadata.name)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-p7bwn (ro)
```
