### ISSUE TITLE
Is it possible to run inside docker

### ISSUE THREAD

**Issue by rucciva** [kubenetworks/kubevpn#196]
Hello, i have successfully run kubevpn directly from my notebook. Now i tried to run it inside docker but doesn't seems to work.

<img width="913" alt="Screenshot 2024-03-27 at 08 49 05" src="https://github.com/kubenetworks/kubevpn/assets/4647473/15daeea0-7666-4394-9dc9-ef0158c8cee5">

I have created custom docker image based on bitnami/kubectl

```
FROM bitnami/kubectl:1.27 AS base 
USER 0
RUN apt update -y && apt install -y curl git ca-certificates unzip
WORKDIR /tmp



FROM base AS kubectl-oidc_login
RUN export ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"; \
    export VERSION="v1.28.0"; \
    curl -sL -o kubelogin.zip "https://github.com/int128/kubelogin/releases/download/${VERSION}/kubelogin_linux_${ARCH}.zip"
RUN unzip kubelogin.zip \
    && mv kubelogin /usr/local/bin/kubectl-oidc_login



FROM base AS kubectl-kubevpn
RUN export ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"; \
    export VERSION="v2.2.3"; \
    curl -sL -o kubevpn.zip "https://github.com/kubenetworks/kubevpn/releases/download/${VERSION}/kubevpn_${VERSION}_linux_${ARCH}.zip" 
RUN unzip kubevpn.zip \
    && mv bin/kubevpn /usr/local/bin/kubectl-kubevpn
COPY --from=kubectl-oidc_login /usr/local/bin/kubectl-oidc_login /usr/local/bin/kubectl-oidc_login
RUN apt-get install -y wget dnsutils vim curl  \
    net-tools iptables iputils-ping lsof iproute2 tcpdump binutils traceroute conntrack socat iperf3 \
    apt-transport-https ca-certificates curl
```

i run it using docker-compose

```
x-base-env: &base-env
  environment:
    KUBECONFIG: ${PWD:-/src}/.kube/kubeconfig.yaml
  volumes:
    - ${PWD:-.}:${PWD:-/src}
  working_dir: ${PWD:-/src}

x-base: &base
  <<: *base-env
  build: .

services:
  start-vpn.sh:
    <<: *base
    build:
      target: kubectl-kubevpn
    privileged: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0 
    entrypoint: [ ./start-vpn.sh ]
```

**Comment by wencaiwulue** [comment]
> Hello, i have successfully run kubevpn directly from my notebook. Now i tried to run it inside docker but doesn't seems to work.
> 
> <img alt="Screenshot 2024-03-27 at 08 49 05" width="913" src="https://private-user-images.githubusercontent.com/4647473/317094084-15daeea0-7666-4394-9dc9-ef0158c8cee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1MDU2NTUsIm5iZiI6MTcxMTUwNTM1NSwicGF0aCI6Ii80NjQ3NDczLzMxNzA5NDA4NC0xNWRhZWVhMC03NjY2LTQzOTQtOWRjOS1lZjAxNThjOGNlZTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMjdUMDIwOTE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjliYmI1MzBjMzIxZGY2YzhkNTY3MGVlMWRlZGJhMTIyMDYyYTM0ZjQxMTMyOTNkZTI5YzY0YWM3OGQ4MGRkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.NMpArifC3nU3V_cXGBrOgW20bezY8a1VbDz-ns68Tsc">
> I have created custom docker image based on bitnami/kubectl
> 
> ```
> FROM bitnami/kubectl:1.27 AS base 
> USER 0
> RUN apt update -y && apt install -y curl git ca-certificates unzip
> WORKDIR /tmp
> 
> 
> 
> FROM base AS kubectl-oidc_login
> RUN export ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"; \
>     export VERSION="v1.28.0"; \
>     curl -sL -o kubelogin.zip "https://github.com/int128/kubelogin/releases/download/${VERSION}/kubelogin_linux_${ARCH}.zip"
> RUN unzip kubelogin.zip \
>     && mv kubelogin /usr/local/bin/kubectl-oidc_login
> 
> 
> 
> FROM base AS kubectl-kubevpn
> RUN export ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')"; \
>     export VERSION="v2.2.3"; \
>     curl -sL -o kubevpn.zip "https://github.com/kubenetworks/kubevpn/releases/download/${VERSION}/kubevpn_${VERSION}_linux_${ARCH}.zip" 
> RUN unzip kubevpn.zip \
>     && mv bin/kubevpn /usr/local/bin/kubectl-kubevpn
> COPY --from=kubectl-oidc_login /usr/local/bin/kubectl-oidc_login /usr/local/bin/kubectl-oidc_login
> RUN apt-get install -y wget dnsutils vim curl  \
>     net-tools iptables iputils-ping lsof iproute2 tcpdump binutils traceroute conntrack socat iperf3 \
>     apt-transport-https ca-certificates curl
> ```
> 
> i run it using docker-compose
> 
> ```
> x-base-env: &base-env
>   environment:
>     KUBECONFIG: ${PWD:-/src}/.kube/kubeconfig.yaml
>   volumes:
>     - ${PWD:-.}:${PWD:-/src}
>   working_dir: ${PWD:-/src}
> 
> x-base: &base
>   <<: *base-env
>   build: .
> 
> services:
>   start-vpn.sh:
>     <<: *base
>     build:
>       target: kubectl-kubevpn
>     privileged: true
>     sysctls:
>       net.ipv6.conf.all.disable_ipv6: 0 
>     entrypoint: [ ./start-vpn.sh ]
> ```

Yes, it support run in docker, i tested it, looks fine. 
<img width="1918" alt="image" src="https://github.com/kubenetworks/kubevpn/assets/33818115/0dc51ad0-8b4f-46bb-afb9-26dbbb4b8191">, 

Here is compose.yaml:
```
x-base-env: &base-env
  environment:
    KUBECONFIG: ${PWD:-/src}/.kube/kubeconfig.yaml
  volumes:
    - ${PWD:-.}:${PWD:-/src}
  working_dir: ${PWD:-/src}

x-base: &base
  <<: *base-env
  image: hub.byted.org/epscprelease/bioos-ide:naisontest

services:
  start-vpn.sh:
    <<: *base
    build:
      target: kubectl-kubevpn
    privileged: true
    sysctls:
      net.ipv6.conf.all.disable_ipv6: 0
    entrypoint: [ ./start-vpn.sh ]
```

start-vpn.sh
```
#!/bin/bash

kubectl-kubevpn connect --foreground
```


but i found some info [stackoverflow](https://stackoverflow.com/questions/64007727/docker-compose-internal-dns-server-127-0-0-11-connection-refused)
