### ISSUE TITLE
`--context` flag is no honored

### ISSUE THREAD

**Issue by rucciva** [kubenetworks/kubevpn#199]
given the following kubeconfig

```
apiVersion: v1
kind: Config
clusters:
  - cluster:
      server: http://localhost:8001
    name: localhost
  - cluster:
      server: http://localhost:8002
    name: localhost2
contexts:
  - name: localhost
    context:
      cluster: localhost
  - name: localhost2
    context:
      cluster: localhost2
current-context: localhost
```

without `--context`, it will use default context (http://localhost:8001)
```bash
$ kubectl kubevpn connect
Error: rpc error: code = Unknown desc = failed to get configmap kubevpn-traffic-manager, err: Get "http://localhost:8001/api/v1/namespaces/default/configmaps/kubevpn-traffic-manager": dial tcp 127.0.0.1:8001: connect: connection refused
```

but with `--context localhost2` (http://localhost:8002), it still try to connect to cluster defined in default context
```bash
$ kubectl kubevpn --context localhost2 connect
Error: rpc error: code = Unknown desc = failed to get configmap kubevpn-traffic-manager, err: Get "http://localhost:8001/api/v1/namespaces/default/configmaps/kubevpn-traffic-manager": dial tcp 127.0.0.1:8001: connect: connection refused
```
