### ISSUE TITLE
What permissions are required if I want to create kubeconfig for other people to use `kubevpn connect`?

### ISSUE THREAD

**Issue by szu17dmy** [kubenetworks/kubevpn#332]
I've installed kubevpn-traffic-manager in a cluster using helm. This cluster will be shared with many developers, so I'm going to create kubeconfigs for everyone. Could you clarify what permissions are needed to use `kubevpn connect`? I cannot find this in the documentation.
Thx.

**Comment by wencaiwulue** [comment]
if you already installed kubevpn server. then kubeconfig should have those permssion is ok

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevpn-traffic-manager
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["*"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
```
