### ISSUE TITLE
The role created by helm chart has no enough permission for client to connect

### ISSUE THREAD

**Issue by artiga033** [kubenetworks/kubevpn#379]
Hi, nice project.

My team works on a cluster which we expect to have permissions as strict as possible. This means we don't even want to provide the clients with permissions like creating pods, etc.. So I deployed kubevpn using helm chart, and according to #332, I would expect that creating a kubeconfig for the service account `kubevpn-traffic-manager` and distribute it to others will be okay. However it seems the permission is not enough (I have do some tests and i will show which permissions are missed later below).

Still i wonder if the service account created by helm chart is for the purpose of creating kubeconfig for clients to use, or it's for internal pods only and i am using it wrongly?

And what's more, the Role provided in https://github.com/kubenetworks/kubevpn/issues/332#issuecomment-2348019063 doesn't seem to work too, at least in my case. It still needs `create pods/portforward` and `create pods/exec` to properly work. Its using an asterisk is also not clear enough and not ensuring minimal permissions.

FYI: Here's how I managed to modify the `kubevpn-traffic-manager` Role created by the helm chart to work as a kubeconfig, as well as corresponding code lines:

- requires `list pods` and `list services` https://github.com/kubenetworks/kubevpn/blob/9edf0122a719c730c0537a1775b06ee7a6f78090/pkg/handler/connect.go#L435

- requires `create pods/portforward` https://github.com/kubenetworks/kubevpn/blob/9edf0122a719c730c0537a1775b06ee7a6f78090/pkg/handler/connect.go#L217

- requires `get pods` and `create pods/exec` https://github.com/kubenetworks/kubevpn/blob/9edf0122a719c730c0537a1775b06ee7a6f78090/pkg/handler/connect.go#L242

**Comment by wencaiwulue** [comment]
NO 

> Hi, nice project.
> 
> My team works on a cluster which we expect to have permissions as strict as possible. This means we don't even want to provide the clients with permissions like creating pods, etc.. So I deployed kubevpn using helm chart, and according to #332, I would expect that creating a kubeconfig for the service account `kubevpn-traffic-manager` and distribute it to others will be okay. However it seems the permission is not enough (I have do some tests and i will show which permissions are missed later below).
> 
> Still i wonder if the service account created by helm chart is for the purpose of creating kubeconfig for clients to use, or it's for internal pods only and i am using it wrongly?
> 
> And what's more, the Role provided in [#332 (comment)](https://github.com/kubenetworks/kubevpn/issues/332#issuecomment-2348019063) doesn't seem to work too, at least in my case. It still needs `create pods/portforward` and `create pods/exec` to properly work. Its using an asterisk is also not clear enough and not ensuring minimal permissions.
> 
> FYI: Here's how I managed to modify the `kubevpn-traffic-manager` Role created by the helm chart to work as a kubeconfig, as well as corresponding code lines:
> 
> * requires `list pods` and `list services` https://github.com/kubenetworks/kubevpn/blob/9edf0122a719c730c0537a1775b06ee7a6f78090/pkg/handler/connect.go#L435
> * requires `create pods/portforward` https://github.com/kubenetworks/kubevpn/blob/9edf0122a719c730c0537a1775b06ee7a6f78090/pkg/handler/connect.go#L217
> * requires `get pods` and `create pods/exec` https://github.com/kubenetworks/kubevpn/blob/9edf0122a719c730c0537a1775b06ee7a6f78090/pkg/handler/connect.go#L242

No you are not wrong.
1. #332 permission is for client usage. attention pod verb "*", means client can list/create/update pod. but  can use more strict. as you say. (list pod,create pods/portforward, get pod, create pod/exec). those permission is minimum
2. helm chart serviceaccount is not use for client, just for server.

**Comment by wencaiwulue** [comment]
Of course, #332 permission is too open, we can make a list to point out which permission is really needs.

**Comment by artiga033** [comment]
As long as I've tested on my local cluster created via [kind](https://kind.sigs.k8s.io/), k8s v1.31.2, `pods` with verb `*` does not cover `create pods/portforward` and `create pods/exec` , so that from #332 is not directly usable, but still needs these two

> helm chart serviceaccount is not use for client, just for server.

Understood, so its my own responsibility to create a service account for kubeconfig to use. Hopefully we can have this use case added to the doc page with a proper set of permissions? I don't think providing average developers with overly open permissions is a good idea.

**Comment by wencaiwulue** [comment]
Ok, got it .

```yaml
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubevpn-traffic-manager
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["pods/portforward", "pods/exec"]
  verbs: ["create"]
```

i made a permission list for client usage, but without tested it 😂
