### ISSUE TITLE
[givsor mode] Use proxy get error: can not found service with selector

### ISSUE THREAD

**Issue by zsq1234** [kubenetworks/kubevpn#439]
k8s service:
```yaml
apiVersion: v1
kind: Service
metadata:
  name: universer
spec:
  type: ClusterIP
  ports:
    - port: 8000
      targetPort: http
      protocol: TCP
      name: http
    - port: 9000
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: universer
    app.kubernetes.io/name: universer
```

deployment labels:
```yaml
      labels:
        app: universer
        app.kubernetes.io/name: universer
        version: ai-chat-flow
```

run proxy command error:
```shell
[abc@localhost]$ ./bin/kubevpn proxy --netstack gvisor -n univer deployment/universer-ai-chat-flow --headers foo=bar
Connected to cluster
Injecting inbound sidecar for deployments.apps/universer-ai-chat-flow
Patching workload deployments.apps/universer-ai-chat-flow
Checking rollout status for deployments.apps/universer-ai-chat-flow
Waiting for deployment spec update to be observed...
Waiting for deployment spec update to be observed...
Waiting for deployment "universer-ai-chat-flow" rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for deployment "universer-ai-chat-flow" rollout to finish: 1 old replicas are pending termination...
Waiting for deployment "universer-ai-chat-flow" rollout to finish: 1 old replicas are pending termination...
Rollout successfully for deployments.apps/universer-ai-chat-flow
Injecting inbound sidecar for deployments.apps/universer-ai-chat-flow failed: can not found service with selector: map[app:universer app.kubernetes.io/name:universer version:ai-chat-flow]
Failed to inject inbound sidecar: can not found service with selector: map[app:universer app.kubernetes.io/name:universer version:ai-chat-flow]
Leaving workload deployments.apps/universer-ai-chat-flow
Error: rpc error: code = Unknown desc = can not found service with selector: map[app:universer app.kubernetes.io/name:universer version:ai-chat-flow]
```

Our environment use Istio service mesh ability, so has multi different deployment with same service.
