### ISSUE TITLE
[BUG] KubeVPN adds a non existant IP in /etc/hosts if a Service is ExternalName

### ISSUE THREAD

**Issue by tehseensajjadsb** [kubenetworks/kubevpn#462]
Creating an ExternalName service in one namespace that routes to another Service in another namespace results in kubevpn not able to use local version of dns name for that service to not work. Instead you must append the same namespace to the address even though the controller you are connected to is in that namesapce.

Example:
```
kind: Service
apiVersion: v1
metadata:
  name: test
  namespace: namespace1
spec:
  type: ExternalName
  externalName: test2.another_namespace.svc.cluster.local
  ports:
  - port: 80
```

```
kubevpn connect -n namespace1
```

```
curl test:80 # Does not work
curl test.namespace1 will work
```

Check `/etc/hosts` file
The IP does not exist in Kubernetes
