### ISSUE TITLE
Why need cluster scope pods list permission?

### ISSUE THREAD

**Issue by SakaZhang** [KubeNetworks/kubevpn#57]
Look this:
```
pods is forbidden: User "system:serviceaccount:NS:NAME" cannot list resource "pods" in API group "" at the cluster scope
```
If this serviceaccount only in ${NS} and has ${NS} permission:
```
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - namespaces
  verbs:
  - get
  - list
  - watch
  - update
  - create
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - secrets
  - pods/portforward
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - patch
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - watch
  - create
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  - rolebindings
  verbs:
  - get
  - list
  - watch
  - create
  - update
```
Now i create a clusterrole below:
```
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
  - get
  - create
  - delete
  - patch
```
and create rolebinding to the serviceaccount${NAME} under ${NS}.

Then exec `kubevpn connect`, it still output: `pods is forbidden: User "system:serviceaccount:minum:minum-dev" cannot list resource "pods" in API group "" at the cluster scope`
