### ISSUE TITLE
error upgrading connection: unable to upgrade connection

### ISSUE THREAD

**Issue by mozhou-tech** [KubeNetworks/kubevpn#65]
=======Following is my error logs=========

$ kubevpn connect                 

get cidr from cluster info...
get cidr from cluster info ok
get cidr from cni...
get cidr from svc...
get cidr from svc ok
traffic manager not exist, try to create it...
pod kubevpn-traffic-manager-f89667975-d4qwg is Pending
Type Reason Message

pod kubevpn-traffic-manager-f89667975-d4qwg is Running
Container     Reason           Message
control-plane ContainerRunning 
vpn           ContainerRunning 
webhook       ContainerRunning 

update ref count successfully
error upgrading connection: unable to upgrade connection: `<html><body><h1>Resource not found</h1></body></html>`
error upgrading connection: unable to upgrade connection: `<html><body><h1>Resource not found</h1></body></html>`
prepare to exit, cleaning up
update ref count successfully
clean up successful

======= Env Info =========
1. K3s
2. Mac Apple M2

**Comment by wencaiwulue** [comment]
It looks like a k8s client-go error，can you try it again? by the way, apple m1 is not support to install k3s, are you using docker?

**Comment by mozhou-tech** [comment]
Referring to official document, arm is supported.
https://docs.k3s.io/?_highlight=arm

And telepresence is worked for me.

**Comment by wencaiwulue** [comment]
➜  ~ curl -sfL https://get.k3s.io | sh -


[ERROR]  Can not find systemd or openrc to use as a process supervisor for k3s
➜  ~ uname
Darwin
➜  ~ uname -m
arm64

Looks like can not install by this way?

**Comment by wencaiwulue** [comment]
did you try `kubevpn connect` again ?

**Comment by wencaiwulue** [comment]
can you provide your kubeconfig and pod cidr and service cidr, let me to locate problem ?

**Comment by mozhou-tech** [comment]
@wencaiwulue yes, i tried `kubevpn connect` many times, following link may help you to install k3s.
https://docs.k3s.io/installation/configuration.

By the way, I installed k3s cluster on top of Parallels Desktop，using openEuler as the VM Guest OS.

And your latest question:

1. kubeconfig
```
apiVersion: v1
clusters:
  - cluster:
      certificate-authority-data: ***
      #   insecure-skip-tls-verify: true
      server: https://10.211.55.4:6443
    name: default
contexts:
  - context:
      cluster: default
      user: default
    name: default
current-context: default
kind: Config
preferences: { }
users:
  - name: default
    user:
      client-certificate-data: xxx
      client-key-data:  xxx
```
2. pod cidr:   10.42.0.0/24
3. service cidr:   10.43.0.0/24

Thanks.
